Imports System.String
Public Class frm_Help
    Private Const homeUrl As String = "http://www.google.com" '"http://helpcentral.componentone.com/maps"

    Private Sub frm_Help_Load(sender As Object, e As EventArgs) Handles Me.Load
        'Dim wdApp As New Microsoft.Office.Interop.Word.Application
        'Dim wdDoc As New Microsoft.Office.Interop.Word.Document

        'wdApp.Visible = False
        '' wdDoc = wdApp.Documents.Open("C:\Users\ydnm\Desktop\Hello.docx", , True)
        'wdDoc = wdApp.Documents.Open(My.Application.Info.DirectoryPath & "\Files\User Manual.docx", , True)

        ''My.Application.Info.DirectoryPath & "\Report\RDLC\rpt_SaleInvoice_Print15.rdl"
        'Dim myText As String = wdDoc.Content.Text
        ''TextBox1.Text = myText

        '' wdDoc = wdApp.Documents.Open("C:\Users\ydnm\Desktop\Hello.docx")
        ''wdDoc.Activate()
        WebBrowser1.Focus()


    End Sub

    Public Sub Open(ByVal FormName As String)

        Dim URL As String = ""
        Select Case FormName

            ''#Master Setup #       

            Case "Location"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Location\Location.html"
                'URL = "D:\YDN(Gold Shop)\User Manual for Package\Location.html"
                lblMessage.Text = "Locatoin" & " - Help"
            Case "GoldQuality"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\GoldQuantity\GoldQuantity.html"
                lblMessage.Text = "Gold Quality" & " - Help"
            Case "ItemCategory"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\ItemCategory\ItemCategory.html"
                lblMessage.Text = "Item Category" & " - Help"
            Case "Customer"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Customer\Customer.html"
                lblMessage.Text = "Customer" & " - Help"
            Case "ItemName"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Item Name\itemname.html"
                lblMessage.Text = "Item Name" & " - Help"
            Case "SaleStaffs"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\SaleStaffs\SaleStaffs.html"
                lblMessage.Text = "Sale Staffs" & " - Help"
            Case "GemsCategory"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Gem Category\gem category.html"
                lblMessage.Text = "Gems Category" & " - Help"
            Case "CurrentPrice"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Current Price\currentprice.html"
                lblMessage.Text = "Current Price" & " - Help"
            Case "CurrentPriceForGold"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\CurrentPriceForGold\currentpriceForGold.html"
                lblMessage.Text = "Current Price For Gold" & " - Help"
            Case "Measurement"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Measurement\measurement.html"
                lblMessage.Text = "Measurement" & " - Help"
            Case "PhotoPath"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Photo path\photopath.html"
                lblMessage.Text = "Photo Path" & " - Help"
            Case "Waste"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Waste\Waste.html"
                lblMessage.Text = "Waste" & " - Help"
            Case "DefineGoldPrice"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\DefineGoldPrice\DefineGoldPrice.html"
                lblMessage.Text = "DefineGoldPrice" & " - Help"
            Case "DefineDiamondPrice"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\DefineDiamondPrice\DefineDiamondPrice.html"
                lblMessage.Text = "DefineDiamondPrice" & " - Help"
            Case "GoldSmith"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\GoldSmith\GoldSmith.html"
                lblMessage.Text = "GoldSmith" & " - Help"
            Case "Supplier"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Supplier\Supplier.html"
                lblMessage.Text = "Supplier" & " - Help"
            Case "CashType"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\CashType\CashType.html"
                lblMessage.Text = "CashType" & " - Help"

                ''#Transaction# 

            Case "SaleItemSetupWithVolume"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\ItemtoSales\ItemtoSales.html"
                lblMessage.Text = "Stock Setup" & " - Help"
            Case "PurchaseRaw"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\PurchaseRaw\PurchaseRaw.html"
                lblMessage.Text = "PurchaseRaw" & " - Help"
            Case "PurchaseStock"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\PurchaseStock\PurchaseStock.html"
                lblMessage.Text = "PurchaseStock" & " - Help"
            Case "SalesGems"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Sale Gems\salegems.html"
                lblMessage.Text = "Sales Gems" & " - Help"
            Case "SaleItemInvoice"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\SaleInvoice\saleinvoice.html"
                lblMessage.Text = "Sale Item Invoice" & " - Help"
            Case "WholeSaleInvoice"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\WholeInvoice\wholesaleinvoice.html"
                lblMessage.Text = "Whole Sale Invoice" & " - Help"
            Case "WholeSaleReturn"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\WholeReturn\wholesalereturn.html"
                lblMessage.Text = "Whole Sale Return" & " - Help"
            Case "ConsignmentSale"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\ConsignmentSale\consignmentsale.html"
                lblMessage.Text = "Consignment Sale" & " - Help"

            Case "SaleVolumeInvoice"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\SaleInvoiceVolume\saleinvoicevolume.html"
                lblMessage.Text = "Sale Invoice (Volume)" & " - Help"

            Case "SaleInvoiceLooseDiamond"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\SaleInvoiceLooseDiamond\SaleInvoiceLooseDiamond.html"
                lblMessage.Text = "Sale Invoice (Loose Diamond)" & " - Help"

            Case "OrderInvoice"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\OrderInvoice\orderinvoice.html"
                lblMessage.Text = "Order Stock " & " - Help"
            Case "OrderInvoiceReturn"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\OrderInvoiceReturn\orderinvoicereturn.html"
                lblMessage.Text = "Order Stock Return" & " - Help"
            Case "MortgageReceive"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\MortgageReceive\mortgagereceive.html"
                lblMessage.Text = "Mortgage Receive " & " - Help"
            Case "MortgageInterest"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\MortgageInterest\mortgageinterest.html"
                lblMessage.Text = "Mortgage Interest " & " - Help"
            Case "MortgagePayback"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\MortgagePayback\mortgagepayback.html"
                lblMessage.Text = "Mortgage Payback " & " - Help"
            Case "MortgageDisable"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\MortgageDisable\mortgagedisable.html"
                lblMessage.Text = "Mortgage Disable " & " - Help"
            Case "MortgageReturn"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\MortgageReturn\mortgagereturn.html"
                lblMessage.Text = "Mortgage Return " & " - Help"
            Case "CashReceiptonCredit"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Cashreceipt\cashreceiptoncredit.html"
                lblMessage.Text = "CashReceipt on Credit" & " - Help"
            Case "DailyExpense"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\DailyExpense\dailyexpense.html"
                lblMessage.Text = "Daily Expense" & " - Help"
            Case "DailyIncome"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Daily Income\dailyincome.html"
                lblMessage.Text = "Daily Income" & " - Help"
            Case "RepairReceive"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\RepairReceive\RepairReceive.html"
                lblMessage.Text = "Repair Receive " & " - Help"
            Case "RepairReturn"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\RepairReturn\RepairReturn.html"
                lblMessage.Text = "Repair Return " & " - Help"

            Case "ReturnAdvance"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\ReturnAdvance\ReturnAdvance.html"
                lblMessage.Text = "Return Advance " & " - Help"

                ''#SystemUtilities# 


            Case "CompanyProfile"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\CompanyProfile\companyprofile.html"
                lblMessage.Text = "Company Profile" & " - Help"
            Case "GenerateFormat"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\GenerateFormat\generateformat.html"
                lblMessage.Text = "Generate Format" & " - Help"
            Case "User"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\User\user.html"
                lblMessage.Text = "User" & " - Help"
            Case "UserMenu"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\UserMenu\usermenu.html"
                lblMessage.Text = "User Menu" & " - Help"
            Case "EventLog"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\EventLogs\eventlogs.html"
                lblMessage.Text = "EventLog" & " - Help"
            Case "DBUtilities"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\DatabaseUtilities\databaseutilities.html"
                lblMessage.Text = "DataBase Utilities" & " - Help"
            Case "BarcodeSetting"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\BarcodeSetting\barcodesetting.html"
                lblMessage.Text = "Barcode Setting" & " - Help"
            Case "Vouchersetting"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\VoucherSetting\vouchersetting.html"
                lblMessage.Text = "Voucher Setting" & " - Help"
            Case "ExportData"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\ExportData\ExportData.html"
                lblMessage.Text = "Export Data" & " - Help"

            Case "GlobalSetting"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\GlobalSetting\globalsetting.html"
                lblMessage.Text = "Global Setting" & " - Help"
          
                ''#Report# 

            Case "PurchaseInvoiceReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\PurchaseReport\PurchaseInvoiceReport.html"
                lblMessage.Text = "Purchase Stock Item Report" & " - Help"
            Case "PurchaseSummaryReportBYDate"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\PurchasebyDate\PurchaseSummaryByDate.html"
                lblMessage.Text = "Purchase Stock Summary By Date Report" & " - Help"
            Case "SalesGemsReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\SalesGemsReport\SalesGemsReport.html"
                lblMessage.Text = "Sales Gems Report" & " - Help"
            Case "SaleVolumeReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\SaleVolumeReport\salesinvoicevolume.html"
                lblMessage.Text = "Sale Invoice (Volume) Report" & " - Help"
            Case "SaleInvoiceReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Sales Invoice Report\salestockrpt.html"
                lblMessage.Text = "Sales Stock Report" & " - Help"
            Case "SaleInvoiceByDateReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\SalebyDate\salesinvoicesummary.html"
                lblMessage.Text = "Sales Summary By Date Report" & " - Help"
            Case "OrderReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\OrderReport\OrderReport.html"
                lblMessage.Text = "Order Invoice Report" & " - Help"
            Case "GemsStockItemReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\GemsStockItemReport\GemsStockItem.html"
                lblMessage.Text = "Gems Stock Item Report" & " - Help"
            Case "SalesItemReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\StockItemsReport\StockItemReport.html"
                lblMessage.Text = "Stock Items Report" & " - Help"
            Case "StockCardReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\StockCardReport\StockCardReport.html"
                lblMessage.Text = "Stock Card Report" & " - Help"
            Case "StockTransactionReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\StockTransactionReport\StockTransactionReport.html"
                lblMessage.Text = "Stock Transaction Report" & " - Help"
            Case "ProfitForSaleItemReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\ProfitStock\ProfitStockItems.html"
                lblMessage.Text = "Profit For Sale Item Report" & " - Help"
            Case "ProfitforVolumeItemReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\ProfitVolume\profitvolumeitems.html"
                lblMessage.Text = "Profit For Volume Item Report" & " - Help"
            Case "CashReceiptReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\CashReceiveOnCreditReport\cashreceiveoncredit.html"
                lblMessage.Text = "Cash Receipt Report " & " - Help"
            Case "DailyExpenseIncomeReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\DailyReport\dailyincomeenpense.html"
                lblMessage.Text = "Daily Expense Income Report" & " - Help"
            Case "GeneralLedgerByLocationReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\GeneralLedger\GeneralLedger.html"
                lblMessage.Text = "General Ledger" & " - Help"
            Case "BarcodeInfo"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\Barcode Info\barcodeinfo.html"
                lblMessage.Text = "BarcodeInfo" & " - Help"
            Case "MasterSetupReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\MasterSetupReport\MasterSetupRpt.html"
                lblMessage.Text = "Master Setup Report" & " - Help"
            Case "CashIn\CashOut"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\CashInCashOut\CashInCashOut.html"
                lblMessage.Text = "CashIn\CashOut" & " - Help"
            Case "SalePercentage"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\SalePercentage\salepercentage.html"
                lblMessage.Text = "Sales Percentage Report" & " - Help"
            Case "DailyTransaction"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\DailyTransaction\dailytransaction.html"
                lblMessage.Text = "Daily Transaction Report" & " - Help"
            Case "RepairReport"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\RepairReport\RepairReceive.html"
                lblMessage.Text = "Repair Stock Report" & " - Help"
            Case "PurchaseFromSupplier"
                URL = My.Application.Info.DirectoryPath & "\HelpBook\PurchaseFromSupplier\PurchaseFromSupplier.html"
                lblMessage.Text = "Purchase From Supplier Report" & " - Help"

                '    Case "ReorderReport"
                '        URL = My.Application.Info.DirectoryPath & "\Help\ReorderReport\Reorder report.html"
                '        lblMessage.Text = "Reorder Report" & " - Help"
                '    Case "SalesReturnReport"
                '        URL = My.Application.Info.DirectoryPath & "\Help\SalesReturnReport\Credit amount report.html"
                '        lblMessage.Text = "Creditor Report" & " - Help"
                '    Case "Applicationoption"
                '        URL = My.Application.Info.DirectoryPath & "\Help\Applicationoption\Application Options.html"
                '        lblMessage.Text = "Applicationoption" & " - Help"
                '    Case "General"
                '        URL = My.Application.Info.DirectoryPath & "\Help\General\General.html"
                '        lblMessage.Text = "General" & " - Help"
                '    Case "Template"
                '        URL = My.Application.Info.DirectoryPath & "\Help\Template\Template.html"
                '        lblMessage.Text = "Template" & " - Help"
                '    Case "DocumentNumber"
                '        URL = My.Application.Info.DirectoryPath & "\Help\DocumentNumber\Document number.html"
                '        lblMessage.Text = "DocumentNumber" & " - Help"
                '    Case "BarCode"
                '        URL = My.Application.Info.DirectoryPath & "\Help\BarCode\BarCode.html"
                '        lblMessage.Text = "BarCode" & " - Help"
                '    Case "LanguageSetup"
                '        URL = My.Application.Info.DirectoryPath & "\Help\LanguageSetup\Language Setup.html"
                '        lblMessage.Text = "Language Setup" & " - Help"
                '    Case "UserMenu"
                '        URL = My.Application.Info.DirectoryPath & "\Help\UserMenu\User Menu.html"
                '        lblMessage.Text = "User Menu" & " - Help"
                '    Case "Users"
                '        URL = My.Application.Info.DirectoryPath & "\Help\Users\User.html"
                '        lblMessage.Text = "User" & " - Help"
                '    Case "ExportMasterSetup"
                '        URL = My.Application.Info.DirectoryPath & "\Help\DataSynchronization\exportmaster.html"
                '        lblMessage.Text = "Export Master Setup" & " - Help"
                '    Case "Export Transaction"
                '        URL = My.Application.Info.DirectoryPath & "\Help\DataSynchronization\ExportTransaction.html"
                '        lblMessage.Text = "Export Transaction" & " - Help"
                '    Case "Import Transaction"
                '        URL = My.Application.Info.DirectoryPath & "\Help\DataSynchronization\Import Transaction.html"
                '        lblMessage.Text = "Import Transaction" & " - Help"
                '    Case "ImportMaserSetup"
                '        URL = My.Application.Info.DirectoryPath & "\Help\DataSynchronization\Importmaster.html"
                '        lblMessage.Text = "Import Maser Setup" & " - Help"
        End Select

        WebBrowser1.Navigate(URL)
        Me.Show()
    End Sub


   
End Class