CREATE TABLE [tbl_TransferReturn](
	[TransferReturnID] TEXT(20) WITH COMPRESSION,
	[TransferReturnDate] DATETIME,
	[Remark] TEXT(100) WITH COMPRESSION,
	[StaffID] TEXT(20) WITH COMPRESSION,
	[LastModifiedLoginUserName] TEXT(50) WITH COMPRESSION,
	[LastModifiedDate] DATETIME,
	[IsUpload] BIT,
	[IsDelete] BIT,
	[CurrentLocationID] TEXT(20) WITH COMPRESSION	
)
GO
CREATE TABLE [tbl_TransferReturnItem](
	[TransferReturnItemID] TEXT(20) WITH COMPRESSION,
	[TransferReturnID] TEXT(20) WITH COMPRESSION,
	[ForSaleID] TEXT(20) WITH COMPRESSION,
	[OriginalFixedPrice] Numeric ,
	[OriginalPriceGram] Numeric,
	[OriginalPriceTK] Numeric,
	[OriginalGemsPrice] Numeric,
	[PriceCode] TEXT(10) WITH COMPRESSION,
	[FixPrice] Numeric,
	[isReturn] Bit
)
GO
CREATE TABLE [tbl_ForSaleGemsItem](
	 [ForSaleGemsItemID] TEXT(20) WITH COMPRESSION,
	 [ForSaleID] TEXT(20) WITH COMPRESSION,
     [GemsCategoryID] TEXT(20) WITH COMPRESSION,
     [GemsName] TEXT(50) WITH COMPRESSION,
     [GemsTK] Decimal(18,13),
     [GemsTG] Decimal(18,13),
     [YOrCOrG] TEXT(20) WITH COMPRESSION,
     [GemsTW] Decimal(18,13),
     [Qty] Numeric,
     [Type] TEXT(20) WITH COMPRESSION,
     [UnitPrice] Numeric,
     [Amount] Numeric,
     [GemsRemark] TEXT(50) WITH COMPRESSION
)
GO
CREATE TABLE [tbl_ForSale](
	[ForSaleID] TEXT(20)WITH COMPRESSION,
	[ItemCode] TEXT(20)WITH COMPRESSION,
	[ItemNameID] TEXT(20) WITH COMPRESSION,
	[Length] TEXT(40) WITH COMPRESSION,
	[ItemCategoryID]TEXT(20) WITH COMPRESSION,
	[GoldQualityID] TEXT(20) WITH COMPRESSION,
	[GivenDate] DateTime,
	[ItemTK] Decimal(18,13),	
	[ItemTG] DECIMAL(18,13),
	[GemsTK]  DECIMAL(18,13),
	[GemsTG] Decimal(18,13),
	[WasteTK] DECIMAL(18,13),
	[WasteTG]  DECIMAL(18,13),
	[GoldTK] DECIMAL(18,13),
	[GoldTG] DECIMAL(18,13),	
	[TotalTK] DECIMAL(18,13),
	[TotalTG] DECIMAL(18,13),
	[IsExit] Bit,
	[ExitDate] DateTime,
	[LastModifiedLoginUserName] TEXT(50) WITH COMPRESSION,
	[LastModifiedDate] DATETIME,
	[Width] TEXT(20) WITH COMPRESSION,
	[IsFixPrice] Bit,
	[FixPrice] Numeric,
	[DesignCharges] Numeric,
	[PlatingCharges] Numeric,
	[MountingCharges] Numeric,
	[WhiteCharges] Numeric,
	[IsOriginalFixedPrice] Bit,
	[OriginalFixedPrice] Numeric,
	[IsOriginalPriceGram] Numeric,
	[OriginalPriceGram] Numeric,
	[OriginalPriceTK] Numeric,
	[OriginalGemsPrice] Numeric,
	[OriginalOtherPrice] Numeric,
	[Photo] TEXT(200) WITH COMPRESSION,
	[SellingPrice] TEXT(50) WITH COMPRESSION,
	[LocationID] TEXT(20) WITH COMPRESSION,
	[IsOrder] Bit,
	[IsClosed] Bit,
	[OrderReceiveDetailID] TEXT(20) WITH COMPRESSION,
	[IsVolume] Bit,
	[Qty] Numeric,
	[StaffID] TEXT(20) WITH COMPRESSION,
	[LossQty] Numeric,
	[LossItemTK] Decimal(18,13),
	[LossItemTG] Decimal(18,13),
	[TotalGemPrice] Numeric,
	[PurchaseWasteTK] Decimal(18,13),
	[PurchaseWasteTG] Decimal(18,13),
	[GoldSmith] TEXT(50) WITH COMPRESSION,
	[Remark] TEXT(200) WITH COMPRESSION,
	[IsDiamond] Bit,
	[OriginalCode] TEXT(20) WITH COMPRESSION,
	[PriceCode] TEXT(20) WITH COMPRESSION,
	[GoldSmithID] TEXT(20) WITH COMPRESSION,
	[Color] TEXT(20) WITH COMPRESSION,
	[IsDelete] Bit,
	[IsSync] Bit,
	[SupplierID] TEXT(20) WITH COMPRESSION,
	[SupplierVou] TEXT(20) WITH COMPRESSION,
	[WReturnDate] DateTime,
	[IsSolidVolume] Bit,
	[SellingRate] Numeric
)
GO
CREATE TABLE [tbl_Transaction] (
	[TransactionName] TEXT(255) WITH COMPRESSION,
	[FromDate] DATETIME NULL,
	[ToDate]  DATETIME NULL,
	[CompanyID] TEXT(50) WITH COMPRESSION
)
GO